version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - ./node_modules/@angular/cli/bin/ng build --configuration=production --build-optimizer
  post_build:
    commands:
      - aws s3 sync dist/chess-on-aws s3://$BUCKET_NAME --delete --acl public-read
